version: '2' 
services:
  livedb:
    image: index.alauda.cn/alaien/srs-db
    ports: 
      - "3306:3306"
  
  srswebclient:
    depends_on:
      - livedb
    image: index.alauda.cn/alaien/srs-web-client
    links:
      - livedb
    ports:
      - "3000:3000"
